---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgC534hx1MNUv7TaR8/TJuH39ubjtnDZQBeZ5KzuoQcJoew6wyJ+YbjgH01AQ19Qeajr58IJCjRoODENCCJWi6yFud6YbzmkcDYIwBvUAzlXm5PAOqd7nvn5xVnvrpJZEyKBUbXdd03H2qqXNOaHL+ogET4QJcqMnCgWDF8lfhyEmUwHW3iqK8nyqfqUFB5OtNgwkMMYKGrWgJfjRrri6zQtjqQyeJbw2enU4Jj85GOI8i5UeWClZWy9BTsmKwaC5d4UssOGqZ3BReaVPF/NimgaVX5LRkGnfTmtRkVvslBdiXYFD5xohBTIwje8P3Y0NeM9M4JLtyUzJwu50lcAJVuw0z874Xfc0ZIfnSf6b3pq7hBg72qWSadDrliwasqwwI3UYrcDzUJpNqsvtlEcs1b3nn8zmemrUOIBDlvRprJSSQF03x1xUZkvUoBs5v22FWErbX6W1MJKlogS0gGup7MdfzOagE20ItI8q9wCiphE8xZqNuMOWGXb6nUHiG/ru3oZURoHtwf8uKhUkMxi2N3b/8RBpLZgUoWYZo1rCzAED9qJzs8ic2ZXKLTbpNaJ9iznA3Klch2K2zYtaawQwGmVu3oGadSS28dBginsfgNnpoIqRHo17KoCDT1Bbrxbn9+8iAVmFmxL4z5B6Ae4P4KITpBzlhN27/L6QoHUL+V7wwgC26ubtMzJ2TpRDkFVG/jSRQN79AkF5edaab1k3vM1AlzUnsssMjPXerKc6KjuqA==
    admin-user: AgDU3DwIUmnlbMpqSSEu2PwcqE0HRGRE5BKj3zm3E+KfEEGnq7Tak3mfHJO92nu9WUvvrt8uawj723k4rzPICEWs/2ymMnEtBYT7pHoaUv+Sp7CR/N33jkRMBDQPVt5rqjjnnRrSIS9TxnWMWAa4Bv8jSvqdlj+5j32Mj/sGuEZ5cmwiduEQfvQqmcFEHPxg05/pKxiQ+E1ctMXwWDJbLWUc1n+ow9djK4RY5vhHC4shOFOWzbOCYKTKYQF7WFMQVG2qWTqaydc/++Z3oUp2K3+fsdJ8YhPpY3EDw2MHgn386DaCe5J/Xrkozh4yhFvYh0wyic+1Zocq585rdY2cE32K8o/R9LLppmn84ZFa+D490+eaRK2EpXDKX4c7ku6ALN4CdU0AC2NkhAWB6BxThcMhJt9/YDsnxflp4raUje4Mxc2ZRK7j42wupm2Kk009uV6S7ZtDW+eYFjJEz+Izzo1KJ0CAw9WEd8vO5+iEyj5UGIemO05uYTUObCaM6hvuW97nUtUB1kt5dZCxZ3ps7bjAI5hDKypfd8aMAlvKUbGi3NT1Y20ElIoWEanGDS67Ua1PYrHGsIoB9RBhOD2VOVQaaaIX7NjqmmAjyARP623EC1ZX5LVYS2AyxC8Wtx1Zx8E2CNe2sQP0u0RbM009HIvQOQknBGm2TiIyHawOX+dOYPjSG0n7s0uuanu4CEDg5iNWKMfZzQ==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
