apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
