---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: mezo
spec:
  encryptedData:
    .dockerconfigjson: AgBmomfls6P8UoeqvQYQyLGNVZeFJnCBwFsOYhF4DwF9d56szMda1MMSjgz+mZqUJ45NQfsWHASAoPfNnAU4vtLsr6uPlgxwGUrFA77559eobipi3jdA5g38SNR5pU22hLeXvhh+WG+vSmFhThnZfUI0nj9MhSC5QhjwezFWHJfevEU2Fb8RnXqt+NRJvlj3IW/v21LQMCqJ0uRMTHRZ0hZ4SntEdBk2fT1D/kTV8uin1cWNQweWkIiiga+9qEsdVwduY9lKkcBPvniWdqV0t7MkB8+0xgnmtBDjJoCg1xbc3EBTeG00hiRo7vdG9kkeYIGbu38bX9EnJ7tZPUgpgEhVbaBkfyY0mRpZztw09ILcMrj59CYFNk/j3EObTKYO1YNpPvB94W4b+gdMCZ2x459Bj3NPIF2WcfwDiMIgVqardF+zn2OdbXbRIdDXkSXTZrjJXJ1PfC/w+qjtNux7nsT21Vuil4LvFtO5eX0r8MwqdjoG7TmTvu6A+I780ZoPU//AeTvSSZ7zDfLvZ3C80v1ULIvTk719jyzmXNQDunDn9Mwc9gJx6XMDZHmQNg7gwtPiMV7a4Fp8+87tGxM5cFMbJttbzJPDqjge6idOFGQvP8TGhQOXKUY6Z0QTeKpYiqDjyhEwWUImu9NaqSjWLFThtYI4ndXZ3ptP9hoI9hStZbMkV+W+CCzhpNEa4HCk/9cr5z4n0cfXr1FSIGFBc9CZiSUixbs75JDIDmY7MJsvITu11TIBbXDtIC1bX7xxXaOrakoLv8mw8r7IqUBzi5CcqiPbZPx/139y4UZWpqngiEXv+JYMjOh6sEgjCWUUEIGuNS+9of3HIRUSLlM0vzK3/T72shbWdC60TGyP/bRt5aDTphiZmjUIqVSwRNodw2UfI1IM57s0W2rMp01+VeaFezsk58fdGtAcgXFC
  template:
    metadata:
      name: ghcr-pull
      namespace: mezo
    type: kubernetes.io/dockerconfigjson
