---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgadmin-auth
  namespace: mezo
spec:
  encryptedData:
    PGADMIN_DEFAULT_EMAIL: AgAMOOL/c7JyT8Ii5Psk8D8nmyyGuR5UtHQebflClL9QzJB+al8c5OpRzD1PoqtdTt31RkXnIawBKg76LdvDbd285JW6JQ0WY0y5VTl6N9Ij38lh+d8LEjsXblfJWemEF4rhQ6tOaeL0mOW1Hhbct/rQ6QY6fU2taCTTz3rv7kTNZvZSctKucxgYNuTjahySq1ygesr+u026vx1Xo7Yf5LfQ2QuLIAb9Cx500EgfZXgb+qPLxvgKgByXMj3nfWbiQvhuzgprEXlnbdHKIGSEyQ88fmzSoSEjU/b1BwdPjgDJOFwLOrd6qNdWan1gzceox5EIXhqFDi2/rOgHfSv/o3extPDUhkXMLCYrBs0UkvsGzNy6aTYU1iuwULxgjFdCnsFWzXG1Pf/O7feRRCfkyh8LQoFdzOO451aIPdoYxi4AKm4iiaXXxTQrvcWny1Nfcq/2DvhMtKfXtihfx+F3Xi+f5bq0amWFq4bAr+jI4t+RnAwmu7dsqc0Vy66T9t1mRKE6oS/HRkyeoxTm3G2J4m5SEg8vwfOFBKwYjWcAvKp7CTfgSDpSqPZlpUOJf4tp/l0BE1rBr+bCe1CXXV1HV+4slXb0r6y6k+PjvfhqsBTCVtKqyGJqjwhixNMwYFpEj15QPXPwHZRKAMDndO5rL4JToNhf5SHRR2HhxaT4W0KAWALTMKp5Zj9TMCABxLal31z8K2ehtbiF9F3B7JFfqAKl7NFNl46Q
    PGADMIN_DEFAULT_PASSWORD: AgARW56XoMHeCMUb7djmd+bSOsTuXmglCt9JC08QrkzMzy8O+KbhmFLjR4/CI6/gXJ/ka+gRWRoygs7wc6bOgepnvCAFB8qzwfXLMKmYjdYpadT7UIPZeAhafwnxYdAkrrEY247l//e6dEPlRWDQVCy3N0AOC5bA8qTJuMljmmhdNAhhWUAwZ98Jifb3YtC+9XpDVZdVrVq/bnUcQHVEtn3pqJj9klqnmVl0gqYzi0L9n1wYqZw6N4vzNiICXDURFBLC37sbDNQIE/9D1TxituTzc7ZFdUuBi8nu7Xtjfh9/4Ix+9g/yaI8WtdoGJjvDMY6BXIHBni92KbNBkTX5NQ/tv1URji9dZGVoRN91GlZ4WUiYilf1ZOPin5YJi9flSXM1Wuob9OV07U5fwQBCuwUt153Iy3B4cmYLb7yb9LQSVI3c9+5nxwpAj+fjVHs7DKTsascYb81LkqA0YbzIYXuCsIe6d/2GXucRJlTpGlSsf6uUOnRhW4t1TarEN4zKv6NETgQTOyH5WE/YOiZOOINO+K80dJYZL/cReLDhHxtZgZBn0FvfzvReUH4KtkxPrPYp8fUDRgz9npKsGmZN1oAW5gafMqG8Fopx6j/MJcniI4OJpwd0OUUVROZPlgJJB9Y9kzGTKWn+rnk3TtgSB1FaS6IH0+w+WO47MygHzAGCMrxhwEEeVwXAN3JHw5sGIMg/DIlk2+fcN2H6cMztY0ti
  template:
    metadata:
      name: pgadmin-auth
      namespace: mezo
    type: Opaque
