import { icon, art } from './art.mjs?v=3';
import { totals, exercises } from './state.mjs?v=3';
import { days, sportNames, runningPlan } from './train-state.mjs?v=3';
export const escapeHtml = s => String(s).replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
const field=(id,label,value,min,max,step=1)=>`<label class="form-field">${label}<input id="${id}" type="number" inputmode="numeric" value="${value}" min="${min}" max="${max}" step="${step}"></label>`;
export function sportForm(kind='volleyball') {
  return `<h2>HOGY MENT?</h2><p>${sportNames[kind]} · ma, szeptember 9.</p><div class="segments">${Object.entries(sportNames).map(([k,n])=>btn('sport-log',n,k===kind?'selected':'',`data-kind="${k}"`)).join('')}</div><div class="form-grid">${field('sport-duration','Idő · perc',kind==='volleyball'?90:45,15,600)}${field('sport-rounds',kind==='volleyball'?'Szettek összesen':'Körök összesen',6,kind==='volleyball'?0:1,50)}${field('sport-rpe','RPE · nehézség',7,1,10)}${kind==='volleyball'?field('sport-shoulder','Váll terhelése · 1–10',5,1,10):''}</div><label class="form-field">Jegyzet<textarea id="sport-notes" maxlength="500" placeholder="Milyen volt az edzés?"></textarea></label>${btn('save-sport',`${icon('check',17)} Sport mentése · +80 XP`,'primary wide',`data-kind="${kind}"`)}`;
}
export function runForm(key) {const r=runningPlan.find(s=>s.key===key);return `<h2>FUTÁS NAPLÓZÁSA</h2><p>${r.title} · ${days[r.day]}, szeptember ${7+r.day}.</p><div class="form-grid">${field('run-rounds','Teljesített körök',r.rounds,0,30)}${field('run-rpe','RPE · nehézség',8,1,10)}</div>${field('run-recovery','Pulzus-megnyugvás · mp',45,0,300,5)}<label class="form-field">Jegyzet<textarea id="run-notes" maxlength="500" placeholder="Milyen volt a tempó?"></textarea></label>${btn('save-run',`${icon('check',17)} Futás mentése · +80 XP`,'primary wide',`data-key="${key}"`)}`;}
export function scheduleForm(){return `<h2>HELYET A MOZGÁSNAK.</h2><p>Adj új sportalkalmat a heti ritmusodhoz.</p><label class="form-field">Nap<select id="slot-day">${days.map((d,i)=>`<option value="${i}" ${i===2?'selected':''}>${d}</option>`).join('')}</select></label><label class="form-field">Sport<select id="slot-kind">${Object.entries(sportNames).map(([k,n])=>`<option value="${k}">${n}</option>`).join('')}</select></label><div class="form-grid"><label class="form-field">Időpont<input id="slot-time" type="time" value="18:00"></label>${field('slot-duration','Időtartam · perc',60,15,600)}</div>${btn('save-slot','Alkalom hozzáadása','primary wide')}`;}
export function mesoForm(){return `<h2>A KÖVETKEZŐ BLOKKOD.</h2><p>Indíts egy Upper / Lower blokkot a mock edzéstervedben.</p><label class="form-field">Mezociklus neve<input id="meso-title" value="Erőalap · Upper / Lower" maxlength="70"></label>${field('meso-weeks','Időtartam · hét',6,3,12)}<p class="body-copy">Hétfő: Alsótest A · Szerda: Felsőtest A · Péntek: Alsótest B. Az utolsó hét deload.</p>${btn('save-meso','Blokk indítása','primary wide')}`;}
const num = n => n.toLocaleString('hu-HU');
const btn = (a, label, cls = '', attrs = '') => `<button type="button" data-action="${a}" class="${cls}" ${attrs}>${label}</button>`;
const goto = (view, label, cls = '', attrs = '') => btn('route', label, cls, `data-view="${view}" ${attrs}`);
const bar = (value, color = '') => `<div class="bar ${color}"><span style="width:${Math.min(100,value)}%"></span></div>`;
const title = (over, name, sub = '') => `<div class="train-title"><div class="eyebrow">${over}</div><h1>${name}</h1>${sub ? `<p>${sub}</p>` : ''}</div>`;
const section = (name, link = '') => `<div class="section-head"><h2>${name}</h2>${link}</div>`;
const smallStats = rows => `<div class="train-stats">${rows.map(([n,l])=>`<div><b>${n}</b><small>${l}</small></div>`).join('')}</div>`;
export function dayStrip(w) { return `<div class="week day-selector">${days.map((d,i)=>btn('select-day', `<small>${['H','K','SZE','CS','P','SZO','V'][i]}</small><strong>${7+i}</strong><span class="day-status">${i===2?icon('bolt',12):i<2?icon('check',12):'·'}</span>`, `day ${i===w.day?'current':''}`, `data-day="${i}" aria-label="${d}, szeptember ${7+i}"`)).join('')}</div>`; }
function gymHero(g,w) { return `<section class="hero hub-hero"><div class="hero-copy"><span class="pill">${icon('gym',12)} MA · 17:00 · MESO W${w.meso.week}/${w.meso.weeks}</span><h2>FELSŐTEST A.<br><em>${g.finished?'MEGCSINÁLTAD.':'ERŐT ÉPÍTÜNK.'}</em></h2><p>${g.finished ? `${g.logs.length} szett · ${num(totals(g).volume)} kg` : 'Mell, hát, váll. Ma egy kicsit<br>tovább lépünk, mint legutóbb.'}</p><div class="hero-meta"><span>${icon('gym',13)} 3 gyakorlat</span><span>${icon('clock',13)} 9 szett · ~35 perc</span></div>${btn(g.finished?'summary':'start', `${g.finished?'Edzés összegzése':g.logs.length?`Folytassuk · ${g.logs.length} szett kész`:'Indítsuk az edzést'} ${icon('arrow',17)}`, 'primary')}</div><div class="hero-art"><div class="orbit"></div>${art(g.finished?'medal':'bell')}</div></section>`; }
function loggedSport(w,kind,day=2) { return w.sportLogs.filter(s=>s.kind===kind&&s.day===day); }
function sessionCard(kind,name,meta,done,action,extra='') { return `<div class="activity-card ${kind}"><div class="activity-icon">${icon(kind==='run'?'run':kind==='gym'?'gym':'ball',24)}</div><div class="activity-copy"><div class="eyebrow">${kind==='run'?'FUTÁS':kind==='gym'?'EDZŐTEREM':'SPORT'} ${done?'· MEGVAN':''}</div><h3>${name}</h3><p>${meta}</p></div>${done?`<span class="done-dot">${icon('check',17)}</span>`:btn(action,icon('plus',17),'round-action',extra.includes('aria-label')?extra:extra+` aria-label="${name} naplózása"`)}</div>`; }
export function trainHome(g,w) {
  const xp=totals(g), extraDone=w.sportLogs.filter(s=>s.day===2).length+w.runLogs.filter(s=>s.key==='wed').length;
  const tiles=[['week','calendar','Heti','A teljes edzésritmusod','cyan'],['mesocycles','gem','Mezociklus',`W${w.meso.week}/${w.meso.weeks} · ${w.meso.phase}`,'purple'],['sport','ball','Sport','Röplabda · Cross · TRX','gold'],['running','run','Futás','Sprint és piramis','cyan'],['exercises','gym','Gyakorlatok','Katalógus és rekordok','lime'],['medals','trophy','Medálok',g.claimed?'Új medál a gyűjteményben':'A fejlődésed nyomai','purple']];
  return title('SZERDA, SZEPTEMBER 9.', 'MA ERŐSEBBEN.', 'Egy helyen a mozgásod. Minden ismétlés számít.') + `<div class="mini-level"><span class="tiny-rank">${xp.level}</span><div><b>Forge atléta <small>${num(g.xp%1200)} / 1 200 XP</small></b>${bar(xp.progress,'purple')}</div>${icon('flame',18)}<strong>${g.finished||extraDone?8:7}</strong></div>` + gymHero(g,w) +
    `<div class="coach-note">${icon('chat',18)}<p><b>Mezo</b> · Ma a fekvenyomásnál +2,5 kg a cél. Tarts meg 2 ismétlést tartalékban.</p>${goto('mezo',icon('arrow',15),'','aria-label="Mezo tanácsa"')}</div>`+
    `<section>${section('MINDEN, AMI MOZGÁS',goto('today',`Mai nap ${icon('arrow',13)}`))}<div class="train-mosaic">${tiles.map(([v,i,n,s,c])=>goto(v,`<span class="tile-art ${c}">${icon(i,28)}</span><span class="tile-label">${n}</span><small>${s}</small><span class="tile-arrow">↗</span>`,'train-tile '+c)).join('')}</div></section>`+
    `<section>${section('MÉG MA',goto('today','Mai áttekintő →'))}${sessionCard('run','Sprint · 6 × 30 mp',w.runLogs.some(r=>r.key==='wed')?'Rögzítve · nézd meg a futásnaplóban':'07:00 · RPE 8–9 · 20 perc',w.runLogs.some(r=>r.key==='wed'),'run-log','data-key="wed"')}${sessionCard('sport','Röplabda',loggedSport(w,'volleyball').length?'Rögzítve · mai sportnapló':'19:00 · 90 perc · csapatedzés',loggedSport(w,'volleyball').length,'sport-log','data-kind="volleyball"')}</section>`+
    `<div class="hub-extras">${btn('custom-workout',`${icon('plus',16)} Saját edzés`,'secondary')}${btn('rewards',`${icon('trophy',16)} Jutalmak`,'secondary')}${btn('skills',`${icon('chart',16)} Skillek`,'secondary')}</div>`;
}
function dayContent(g,w) {
  const d=w.day, run=runningPlan.find(r=>r.day===d), sport=w.sportSchedule.filter(s=>s.day===d);
  return `${[0,2,4].includes(d)?(d===2?gymHero(g,w):sessionCard('gym',d===0?'Alsótest A':'Alsótest B',d<2?'Befejezve · 12 szett':'17:00 · 4 gyakorlat · 12 szett',d<2,'planned','aria-label="Tervezett edzés"')):''}${run?sessionCard('run',run.title,`${run.time} · ${run.rounds} kör · RPE ${run.rpe}`,w.runLogs.some(r=>r.key===run.key),d>2?'planned':'run-log',`data-key="${run.key}" aria-label="Futás naplózása"`):''}${sport.map(s=>sessionCard('sport',sportNames[s.kind],`${s.time} · ${s.duration} perc`,loggedSport(w,s.kind,d).length,d>2?'planned':d<2?'past-sport':'sport-log',`data-kind="${s.kind}" aria-label="${sportNames[s.kind]} naplózása"`)).join('')}${![0,2,4].includes(d)&&!run&&!sport.length?`<div class="panel recovery-card">${icon('leaf',40)}<h2>A PIHENÉS IS ÉPÍT.</h2><p>Erre a napra nincs tervezett edzés.</p>${d===2?btn('custom-workout','+ Saját edzés','secondary'):''}</div>`:''}`;
}
function weekPage(g,w) { return title('EDZÉS / HETI','A HETI RITMUSOD.','Erő, sport és futás. Egy közös naptárban.')+smallStats([['3','GYM'],[w.sportSchedule.length,'SPORT'],['3','FUTÁS']])+days.map((d,i)=>{const sessions=[...([0,2,4].includes(i)?[{kind:'gym',name:i===2?'Felsőtest A':'Alsótest',time:'17:00'}]:[]),...w.sportSchedule.filter(s=>s.day===i).map(s=>({kind:'sport',name:sportNames[s.kind],time:s.time})),...runningPlan.filter(s=>s.day===i).map(s=>({kind:'run',name:s.title,time:s.time}))].sort((a,b)=>a.time.localeCompare(b.time));return `<button class="week-agenda ${i===2?'today':''}" data-action="select-day" data-day="${i}"><span class="agenda-day"><b>${d}</b><small>${7+i}. ${i===2?'· MA':''}</small></span><span class="agenda-items">${sessions.length?sessions.map(s=>`<span class="agenda-item ${s.kind}">${icon(s.kind==='run'?'run':s.kind==='gym'?'gym':'ball',14)}<b>${s.name}</b><small>${s.time}</small></span>`).join(''):'<span class="muted">Pihenő · regeneráció</span>'}</span>${icon('arrow',14)}</button>`;}).join(''); }
function mesoPage(g,w,detail=false) {
  return title('EDZÉS / MEZOCIKLUS',detail?'ÉPÍTSD FEL A HETED.':'HOSSZÚ TÁVON ERŐS.',detail?escapeHtml(w.meso.title):'A terved, az aktuális terhelésed és a fejlődésed.')+
  `<section class="meso-poster panel"><div class="eyebrow">AKTÍV MEZOCIKLUS</div><h2>${escapeHtml(w.meso.title)}</h2>${art('gem','meso-art')}<p>${w.meso.weeks} hét · 3 edzés / hét</p><div class="meso-arc">${Array.from({length:w.meso.weeks},(_,i)=>`<div class="${i===w.meso.week-1?'active':''}"><i style="height:${i===w.meso.weeks-1?25:35+i*10}px"></i><small>W${i+1}</small></div>`).join('')}</div><div class="meso-phase">${w.meso.phase} <span>W${w.meso.week} / ${w.meso.weeks} · záróhét: deload</span></div>${!detail?goto('meso-detail',`Aktuális mezociklus ${icon('arrow',16)}`,'primary wide'):''}</section>`+
  (detail?`<div class="week-pills">${Array.from({length:w.meso.weeks},(_,i)=>btn('meso-week',`W${i+1}`,w.mesoWeek===i+1?'selected':'',`data-week="${i+1}"`)).join('')}</div>${section(`${w.mesoWeek}. HÉT · EDZÉSNAPOK`)}${[['Hétfő','Alsótest A'],['Szerda','Felsőtest A'],['Péntek','Alsótest B']].map(([d,n])=>btn('meso-day',`<span class="quest-icon">${icon('gym',20)}</span><span><small>${d}</small><b>${n}</b><p>3 gyakorlat · 9 munkasorozat</p></span>${icon('arrow',16)}`,'detail-row',`data-title="${n}"`)).join('')}${section('HETI IZOMTERHELÉS')}${[['Mell',9,14],['Hát',12,16],['Váll',9,12],['Láb',12,18]].map(([n,v,max])=>btn('muscle',`<span><b>${n}</b><small>${v} / ${max} szett</small></span>${bar(v/max*100,'purple')}`,'muscle-row',`data-name="${n}"`)).join('')}`:
  `<div class="train-mosaic">${goto('meso-detail',`${icon('chart',27)}<span class="tile-label">Heti terhelés</span><small>Izomcsoportonként</small>`,'train-tile purple')}${btn('templates',`${icon('grid',27)}<span class="tile-label">Sablonok</span><small>Válassz következő blokkot</small>`,'train-tile cyan')}</div>${btn('new-meso',`${icon('plus',16)} Új mezociklus tervezése`,'secondary wide')}`);
}
function sportPage(g,w) {
  const recent=w.sportLogs.filter(s=>s.kind===w.sportKind), mins=recent.reduce((n,s)=>n+s.duration,0);
  const tabs=[['plan','Heti terv'],['log','Napló'],['load','Cross-load']];
  return title('EDZÉS / SPORT','JÁTÉKBAN VAGY.', 'Röplabda, Cross és TRX — mindnek megvan a helye.')+`<div class="sport-hero panel">${art('ball')}<span class="pill">MOZGÁS, AMI FELTÖLT</span><h2>${sportNames[w.sportKind].toUpperCase()}</h2><p>Erőn túl. Együtt, lendületből.</p>${btn('sport-log',`${icon('plus',16)} Sport naplózása`,'primary',`data-kind="${w.sportKind}"`)}</div><div class="segments">${Object.entries(sportNames).map(([k,n])=>btn('sport-kind',n,w.sportKind===k?'selected':'',`data-kind="${k}"`)).join('')}</div>`+smallStats([[recent.length,'ALKALOM'],[mins,'PERC'],[recent.length?(recent.reduce((n,s)=>n+s.rpe,0)/recent.length).toFixed(1):'—','ÁTLAG RPE']])+`<div class="segments muted-segments">${tabs.map(([k,n])=>btn('sport-tab',n,w.sportTab===k?'selected':'',`data-tab="${k}"`)).join('')}</div>`+
  (w.sportTab==='plan'?w.sportSchedule.filter(s=>s.kind===w.sportKind).map(s=>`<div class="detail-row"><span class="quest-icon gold">${icon('calendar',22)}</span><span><small>${days[s.day]} ${s.day===2?'· MA':''}</small><b>${sportNames[s.kind]}</b><p>${s.time} · ${s.duration} perc</p></span>${s.day===2?btn('sport-log','+ Log','text-btn',`data-kind="${s.kind}"`):''}</div>`).join('')+btn('schedule','+ Alkalom a heti tervbe','secondary wide'):
  w.sportTab==='log'?(recent.length?recent.map(s=>`<div class="detail-row"><span class="quest-icon gold">${icon('check',20)}</span><span><small>${days[s.day]} · ${sportNames[s.kind]}</small><b>${s.duration} perc · RPE ${s.rpe}</b><p>${s.rounds} ${s.kind==='volleyball'?'szett':'kör'}${s.kind==='volleyball'?` · váll ${s.shoulder}/10`:''}</p>${s.notes?`<p>${escapeHtml(s.notes)}</p>`:''}</span></div>`).join(''):'<div class="empty-state">Még nincs rögzített alkalom ebből a sportból.</div>'):
  `<div class="panel"><div class="eyebrow">BECSÜLT KIEGÉSZÍTŐ TERHELÉS</div><h3>Az edzéseid összeadódnak.</h3><p class="body-copy">A ${sportNames[w.sportKind]} fő érintett izomcsoportjai. Szemléltető terhelési arányok.</p>${[['Váll',72],['Láb',55],['Törzs',48]].map(([n,v])=>`<div class="load-row"><span>${n}</span>${bar(v,'purple')}</div>`).join('')}</div>`);
}
function runningPage(g,w) {
  return title('EDZÉS / FUTÁS','TALÁLD MEG A TEMPÓD.','Intervallumok, amik előrevisznek.')+`<section class="run-hero panel">${art('shoe')}<span class="pill">AKTÍV FUTÓBLOKK</span><h2>SPRINT &<br>PYRAMID.</h2><p>3. hét / 6 · heti 3 alkalom</p><div class="run-wave">${[20,30,45,30,20,20,30,45,30,20].map(h=>`<i style="height:${h}px"></i>`).join('')}</div></section>`+smallStats([[w.runLogs.length,'RÖGZÍTETT'],['3 / 6','HÉT'],[w.runLogs.at(-1)?.recovery??'—','HR RECOVERY · MP']])+`<div class="segments"><button data-action="run-tab" data-tab="plan" class="${w.runTab==='plan'?'selected':''}">E heti edzés</button><button data-action="run-tab" data-tab="log" class="${w.runTab==='log'?'selected':''}">Napló</button></div>`+
  (w.runTab==='plan'?runningPlan.map(r=>{const l=w.runLogs.find(s=>s.key===r.key);return `<section class="panel run-session"><div class="eyebrow">${days[r.day]} · ${r.time} ${r.day===2?'· MA':''}</div><h3>${r.title}</h3><p>${r.rounds} kör · RPE ${r.rpe}${r.title.startsWith('Piramis')?' · pihenő = szakasz × 2':''}</p>${l?`<div class="logged-band">${icon('check',16)} Kész · ${l.rounds} kör · RPE ${l.rpe}</div>`:btn('run-log',r.day>2?'Tervezett alkalom':r.day<2?'Pótold a futást':'Naplózd a futást','primary wide',`data-key="${r.key}" ${r.day>2?'disabled':''}`)}</section>`;}).join(''):
  w.runLogs.map(l=>`<div class="detail-row"><span class="quest-icon cyan">${icon('run',21)}</span><span><small>${runningPlan.find(r=>r.key===l.key)?.title}</small><b>${l.rounds} kör · RPE ${l.rpe}</b><p>Pulzus-megnyugvás: ${l.recovery} mp</p><p>${escapeHtml(l.notes)}</p></span>${icon('check',16)}</div>`).join('')+`<div class="panel"><div class="eyebrow">PULZUS-MEGNYUGVÁS</div><p class="body-copy">A rögzített alkalmak értékei, másodpercben.</p><div class="recovery-trend">${w.runLogs.map(l=>`<div><i style="height:${Math.max(6,Math.min(100,l.recovery))}px"></i><b>${l.recovery} mp</b></div>`).join('')}</div></div>`);
}
export const catalog=[...exercises.map(e=>({...e,group:e.name==='Fekvenyomás'?'Mell':e.name==='Evezés csigán'?'Hát':'Váll'})),{name:'Guggolás',group:'Láb',muscle:'Combfeszítő · farizom',kg:70,reps:8},{name:'Román felhúzás',group:'Láb',muscle:'Combhajlító · farizom',kg:65,reps:10},{name:'Oldalemelés',group:'Váll',muscle:'Oldalsó delta',kg:8,reps:15}];
export function catalogRows(w){return catalog.filter(e=>(w.exerciseFilter==='Összes'||w.exerciseFilter===e.group)&&e.name.toLocaleLowerCase('hu').includes(w.exerciseSearch.toLocaleLowerCase('hu'))).map(e=>btn('exercise',`<span class="catalog-icon">${icon('gym',25)}</span><span><b>${e.name}</b><small>${e.muscle}</small><em>Előző: ${e.kg} kg × ${e.reps}</em></span>${icon('arrow',16)}`,'detail-row',`data-name="${e.name}"`)).join('')||'<p class="empty-state">Nincs ilyen gyakorlat.</p>';}
export function renderTrainPage(view,g,w){
  if(view==='home')return trainHome(g,w);
  if(view==='today')return title('EDZÉS / NAPI ÁTTEKINTŐ',w.day===2?'A MAI MOZGÁSOD.':days[w.day].toUpperCase()+'.')+dayStrip(w)+goto('meso-detail',`${icon('gem',17)} ${escapeHtml(w.meso.title)} · W${w.meso.week} ${icon('arrow',14)}`,'meso-link')+dayContent(g,w)+(w.day===2?btn('custom-workout','+ Saját edzés','secondary wide'):'');
  if(view==='week')return weekPage(g,w);
  if(view==='mesocycles'||view==='meso-detail')return mesoPage(g,w,view==='meso-detail');
  if(view==='sport')return sportPage(g,w);
  if(view==='running')return runningPage(g,w);
  if(view==='exercises')return title('EDZÉS / GYAKORLATOK','ISMERD A MOZGÁST.','Gyakorlatok, előző súlyok és technika.')+`<input class="search-field" id="exercise-search" aria-label="Gyakorlat keresése" placeholder="Gyakorlat keresése…" value="${escapeHtml(w.exerciseSearch)}"><div class="filter-chips">${['Összes','Mell','Hát','Váll','Láb'].map(n=>btn('exercise-filter',n,w.exerciseFilter===n?'selected':'',`data-filter="${n}"`)).join('')}</div><div id="catalog-list">${catalogRows(w)}</div>`;
  if(view==='medals')return title('EDZÉS / MEDÁLOK','EZT TE ÉRTED EL.','A konzisztencia látható nyomai.')+`<div class="medal-grid">${[['medal','Hétnapos lendület',true],['chest','Forge Initiate',g.claimed],['gem','Visszatérő futó',w.runLogs.length>=2],['ball','Csapatjátékos',w.sportLogs.some(s=>s.kind==='volleyball')]].map(([a,n,done])=>btn('medal-detail',`${art(a)}<b>${n}</b><small>${done?'MEGSZEREZVE':'MÉG ELŐTTED ÁLL'}</small>`,'medal-item '+(done?'earned':'locked'),`data-title="${n}" data-earned="${done}"`)).join('')}</div>`;
  return title('MEZO / KÖRNYEZETI ELŐNÉZET',({nap:'A MAI NAPOD.',fuel:'ÜZEMANYAG.',mezo:'EGYÜTT HALADUNK.',me:'EZ VAGY TE.'})[view]||'MEZO.')+`<section class="panel context-panel">${icon(({nap:'sun',fuel:'leaf',mezo:'chat',me:'user'})[view]||'grid',38)}<h2>${({nap:'Mozgás a napodban',fuel:'Edzés körüli üzemanyag',mezo:'Mezo, a társad',me:'A fejlődésed'})[view]}</h2><p class="body-copy">${view==='mezo'?'„A mai felsőtest-edzés és az esti röplabda együtt terheli a vállad. A sorozatoknál figyelj a tartalékra.”':view==='fuel'?'A mai edzésed: Felsőtest A, 17:00. A Fuel az edzésritmusodhoz kapcsolódik.':view==='nap'?'17:00 · Felsőtest A. 19:00 · Röplabda. A Trainből rögzített mozgás itt is megjelenik.':`Forge atléta · ${totals(g).level}. szint. Mai edzés: ${g.finished?'befejezve':g.logs.length?'folyamatban':'előtted áll'}.`}</p><p class="context-note">Ez a fül a fő navigáció kontextusát mutatja. Ebben a prototípusban az Edzés felületei járhatók be részletesen.</p>${goto('home',`Vissza az Edzéshez ${icon('arrow',16)}`,'primary wide')}</section>`;
}
