/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with the owner credentials, returns a JWT */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/biometrics/weight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All weight logs of the current user, date ascending */
        get: operations["listWeightLogs"];
        put?: never;
        /** Log a weight entry */
        post: operations["logWeight"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/biometrics/sleep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All sleep logs of the current user, date ascending */
        get: operations["listSleepLogs"];
        put?: never;
        /** Log a sleep entry */
        post: operations["logSleep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/biometrics/checkin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check-ins of the current user for one day */
        get: operations["listCheckInsForDay"];
        put?: never;
        /** Upsert a check-in slot (find-or-new on date + slotTime) */
        post: operations["saveCheckIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Error contract returned by GlobalExceptionHandler (see error_handling.md). Every non-2xx response body is an array of SystemMessage. */
        SystemMessage: {
            /** @enum {string} */
            level?: "ERROR" | "WARNING" | "INFO";
            /**
             * @description Machine-readable error code resolved via messages.properties
             * @example VALIDATION_REQUIRED_FIELD
             */
            code: string;
            params?: string[];
            /** @description Resolved human-readable message (English) */
            message?: string;
            /** @description Offending field for FIELD-type messages */
            fieldName?: string;
            /** @enum {string} */
            type: "REQUEST" | "FIELD";
            /** Format: uuid */
            exceptionTraceId?: string;
        };
        SystemMessageList: components["schemas"]["SystemMessage"][];
        LoginRequest: {
            /**
             * Format: email
             * @example owner@mezo.local
             */
            email: string;
            password: string;
        };
        TokenResponse: {
            /** @description HS256-signed JWT bearer token */
            token: string;
        };
        LogWeightRequest: {
            /** Format: date */
            date: string;
            /** @description Weight in kilograms (max 3 integer + 2 fraction digits) */
            weightKg: number;
            note?: string;
        };
        WeightLogResponse: {
            /** Format: uuid */
            id: string;
            /** Format: date */
            date: string;
            /** @description Weight in kilograms (frontend field name) */
            value: number;
            note?: string;
        };
        LogSleepRequest: {
            /** Format: date */
            date: string;
            /**
             * @description Bedtime as HH:mm
             * @example 23:10
             */
            bedtime?: string;
            /**
             * @description Wake-up time as HH:mm
             * @example 06:45
             */
            wakeup?: string;
            /** @description Sleep duration in hours (max 2 integer + 2 fraction digits) */
            durationH?: number;
            quality?: number;
            awakenings?: number;
            note?: string;
        };
        SleepLogResponse: {
            /** Format: uuid */
            id: string;
            /** Format: date */
            date: string;
            bedtime?: string;
            wakeup?: string;
            /** @description Sleep duration in hours (frontend field name) */
            duration?: number;
            quality?: number;
            awakenings?: number;
            /** @description Hours between last meal and sleep — always 0 until Fuel lands */
            mealToSleep: number;
            notes?: string;
        };
        SaveCheckInRequest: {
            /** Format: date */
            date: string;
            /** @description Slot identifier as shown in the UI (e.g. "08:00") */
            slotTime: string;
            state: string;
            energy?: number;
            stress?: number;
            body?: number;
            mental?: number;
            note?: string;
        };
        CheckInResponse: {
            /** Format: uuid */
            id: string;
            /** Format: date */
            date: string;
            slotTime: string;
            state: string;
            energy?: number;
            stress?: number;
            body?: number;
            mental?: number;
            note?: string;
            /** Format: date-time */
            savedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description JWT issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation failure */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemMessageList"];
                };
            };
            /** @description Invalid credentials (AUTH_LOGIN_INVALID_CREDENTIALS) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemMessageList"];
                };
            };
        };
    };
    listWeightLogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Weight logs, ordered by date ascending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeightLogResponse"][];
                };
            };
            /** @description Missing/invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemMessageList"];
                };
            };
        };
    };
    logWeight: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogWeightRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeightLogResponse"];
                };
            };
            /** @description Validation failure */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemMessageList"];
                };
            };
            /** @description Missing/invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemMessageList"];
                };
            };
        };
    };
    listSleepLogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sleep logs, ordered by date ascending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SleepLogResponse"][];
                };
            };
            /** @description Missing/invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemMessageList"];
                };
            };
        };
    };
    logSleep: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogSleepRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SleepLogResponse"];
                };
            };
            /** @description Validation failure */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemMessageList"];
                };
            };
            /** @description Missing/invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemMessageList"];
                };
            };
        };
    };
    listCheckInsForDay: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Check-ins for the given day */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInResponse"][];
                };
            };
            /** @description Missing/invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemMessageList"];
                };
            };
        };
    };
    saveCheckIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveCheckInRequest"];
            };
        };
        responses: {
            /** @description Saved (upsert — 200, not 201) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInResponse"];
                };
            };
            /** @description Validation failure */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemMessageList"];
                };
            };
            /** @description Missing/invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemMessageList"];
                };
            };
        };
    };
}
